[workouts.workout1]
    name="Workout1"
    [workouts.workout1.days.day1]
        description="First Day"
        day=1
        [workouts.workout1.days.day1.exercises.exercise1]
            exercise="Front Squats"
            reps=12
        [workouts.workout1.days.day1.exercises.exercise2]
            exercise="Rack Deadlift"
            reps=15
        [workouts.workout1.days.day1.exercises.exercise3]
            exercise="Crunches"
            reps=12